from cocktails.models import Ingredient, Cocktail, RecipeDetail

Quantity.objects.all().delete()
Ingredient.objects.all().delete()
Cocktail.objects.all().delete()

sugarcube = Ingredient(name = 'Sugarcube', category = 'sweetener')
sugarcube.save()
angostura = Ingredient(name = 'Angostura bitters', category = 'bitters')
angostura.save()
bourbon = Ingredient(name = 'Bourbon', category = 'spirit')
bourbon.save()
lemon = Ingredient(name = 'Lemon', category = 'garnish')
lemon.save()
orange = Ingredient(name = 'Orange', category = 'garnish')
orange.save()


COF = Cocktail(name = 'Classic Old-Fashioned', bartender = 'CLASSIC')
COF.save()
quant_COF = RecipeDetail(ingredient = sugarcube, cocktail = COF, quantity = 1)
quant_COF.save()
quant_COF = RecipeDetail(ingredient = angostura, cocktail = COF, quantity = 2, unit = 'dash')
quant_COF.save()
quant_COF = RecipeDetail(ingredient = bourbon, cocktail = COF, quantity = 2, unit = 'oz')
quant_COF.save()
quant_COF = RecipeDetail(ingredient = lemon, cocktail = COF, quantity = 1, unit = 'twist')
quant_COF.save()
quant_COF = RecipeDetail(ingredient = orange, cocktail = COF, quantity = 1, unit = 'twist')
quant_COF.save()
