# Generated by Django 4.0.6 on 2022-11-01 01:01

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('classic', 'Classic & Vintage'), ('gin-SH', 'Gin Shaken'), ('gin-ST', 'Gin Stirred'), ('rum-SH', 'Rum Shaken'), ('rum-ST', 'Rum Stirred'), ('agave-SH', 'Agave Shaken'), ('agave-ST', 'Agave Stirred'), ('whi-SH', 'Whiskey Shaken'), ('whi-ST', 'Whiskey Stirred'), ('bra-SH', 'Brandy Shaken'), ('bra-ST', 'Brandy Stirred'), ('SC', 'Sparkling Cocktail'), ('FWC', 'Fortified Wine Cocktails'), ('punch', 'Punch'), ('jul', 'Julep'), ('fizz', 'Flips and Fizzes'), ('swiz', 'Swizzles'), ('aqua', 'Aquavit'), ('Saz-V', 'Sazerac Variation'), ('Neg-V', 'Negroni Variation'), ('daq-V', 'Daiquiri Variation'), ('man-V', 'Manhattan Variation'), ('OF-V', 'Old Fashioned Variation')], max_length=142)),
                ('bartender', models.CharField(blank=True, max_length=40)),
                ('glassware', models.CharField(blank=True, choices=[('single', 'Single Rocks Glass'), ('double', 'Double Rocks Glass'), ('coupe', 'Coupe'), ('NN', 'Nick & Nora'), ('martini', 'Martini Glass'), ('collins', 'Collins Glass'), ('beer', 'Beer Glass'), ('fizz', 'Fizz Glass'), ('julep', 'Julep Tin'), ('port', 'Port'), ('flute', 'Flute'), ('tiki', 'Tiki Mug'), ('HB', 'Highball'), ('snif', 'Snifter')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('method', models.TextField(blank=True)),
                ('variations', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('spirits', 'Spirits'), ('modifiers', (('liqueur', 'Liqueur'), ('amaro', 'Amaro'), ('wine', 'Fortified Wine'))), ('bitters', 'Bitters'), ('sweetener', 'Sweetener'), ('citrus', 'Citrus'), ('toppers', 'Toppers'), ('emulsifier', 'Emulsifier'), ('muddler', 'Muddler'), ('garnish', 'Garnish'), ('other', (('concentrate', 'Concentrate'), ('infusion', 'Infusion'), ('cordial', 'Cordial'), ('solutions', 'Solutions'), ('tinctures', 'Tinctures'), ('puree', 'Purees')))], max_length=83)),
                ('notes', models.TextField(blank=True)),
                ('related', models.ManyToManyField(blank=True, related_name='related_ingredient', to='cocktails.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True)),
                ('unit', models.CharField(blank=True, choices=[('oz', 'ounce(s)'), ('ml', 'milliliter(s)'), ('g', 'gram(s)'), ('tsp', 'teaspoon(s)'), ('tbsp', 'tablespoon(s)'), ('dash', 'dash(es)'), ('barspoon', 'barspoon(s)'), ('pinch', 'pinch(es)'), ('bunch', 'bunch(es)'), ('slice', 'slice(s)'), ('twist', 'twist'), ('peel', 'peel'), ('wheel', 'wheel'), ('wedge', 'wedge'), ('rinse', 'rinse'), ('rim', 'rim')], max_length=15)),
                ('recommended', models.CharField(blank=True, max_length=40)),
                ('optional', models.BooleanField(blank=True, null=True)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.ingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'cocktail', 'recommended')},
            },
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='cocktails.RecipeDetail', to='cocktails.ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='related_cocktail', to='cocktails.cocktail'),
        ),
    ]
