# Generated by Django 4.0.6 on 2022-09-01 22:55

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bartender', models.CharField(blank=True, max_length=40)),
                ('flavor_profile', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('astringent', 'Astringent'), ('bitter', 'Bitter'), ('boozy', 'Boozy'), ('complex', 'Complex'), ('fresh', 'Fresh'), ('rich', 'Rich'), ('salty', 'Salty'), ('sharp', 'Sharp'), ('silky', 'Silky'), ('smoky', 'Smoky'), ('sour', 'Sour'), ('spicy', 'Spicy'), ('subtle', 'Subtle'), ('sweet', 'Sweet'), ('tannic', 'Tannic'), ('umami', 'Umami')], max_length=103)),
                ('decription', models.TextField(blank=True)),
                ('method', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('spirit', 'Spirit'), ('liquor', 'Liquor'), ('sweetener', 'Sweetener'), ('citrus', 'Citrus'), ('soda', 'Soda'), ('emulsifier', 'Emulsifier'), ('muddler', 'Muddler'), ('bitters', 'Bitters'), ('garnish', 'Garnish'), ('concentrate', 'Concentrate'), ('infusion', 'Infusion'), ('cordial', 'Cordial'), ('solutions', 'Solutions'), ('tinctures', 'Tinctures')], max_length=119)),
                ('flavor_profile', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('astringent', 'Astringent'), ('bitter', 'Bitter'), ('boozy', 'Boozy'), ('complex', 'Complex'), ('fresh', 'Fresh'), ('rich', 'Rich'), ('salty', 'Salty'), ('sharp', 'Sharp'), ('silky', 'Silky'), ('smoky', 'Smoky'), ('sour', 'Sour'), ('spicy', 'Spicy'), ('subtle', 'Subtle'), ('sweet', 'Sweet'), ('tannic', 'Tannic'), ('umami', 'Umami')], max_length=103)),
                ('decription', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(blank=True, choices=[('oz', 'Ounce(s)'), ('ml', 'Milliliter(s)'), ('g', 'Gram(s)'), ('tsp', 'Teaspoon(s)'), ('tbsp', 'Tablespoon(s)'), ('dash', 'Dash(es)'), ('barspoon', 'Barspoon(s)'), ('pinch', 'Pinch(es)'), ('bunch', 'Bunch')], max_length=15)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(through='cocktails.Quantity', to='cocktails.ingredient'),
        ),
    ]
