# Generated by Django 4.0.6 on 2022-09-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='unit',
            field=models.CharField(blank=True, choices=[('oz', 'ounce(s)'), ('ml', 'milliliter(s)'), ('g', 'gram(s)'), ('tsp', 'teaspoon(s)'), ('tbsp', 'tablespoon(s)'), ('dash', 'dash(es)'), ('barspoon', 'barspoon(s)'), ('pinch', 'pinch(es)'), ('bunch', 'bunch(es)'), ('twist', 'twist(s)'), ('peel', 'peel(s)')], max_length=15),
        ),
    ]
