# Generated by Django 4.0.6 on 2022-09-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_alter_quantity_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quantity',
            new_name='RecipeDetail',
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='decription',
            new_name='description',
        ),
    ]
